api:
  port: 9000
  cors: true
  basicAuth:
    name: admin
    password: public

db:
  type: mysql
  mysql:
    host: mysql
    port: 3306
    user: tio
    password: public
    db: tio
    charset: utf8
    timezone: Asia%2FShanghai
    maxIdleConns: 4
    maxOpenConns: 50
    connMaxLifetime: 60
    showSql: false

connector:
  type: nats
  nats:
    server:
      serverName: tio-node-2
      clusterName: tio
      port: 4222
      clusterPort: 6222
      routes:
        - nats://tio-node-1:6222
        - nats://tio-node-3:6222
      mqttPort: 1883
      wsPort: 8083
      storeDir: ./data/nats/tio-node-2
      jetStreamMaxMemory: 268435456
      jetStreamMaxStore: 1073741824
      mqttStreamReplicas: 3
      presenceReplicas: 3
      clusterUser: $tio-route
      clusterPassword: public
    appClient:
      user: $tio-app
      password: public
    systemClient:
      user: $tio-sys
      password: public
    mqttPublisher:
      user: $tio-mqtt-publisher
      password: public
    superUsers:
      - name: $biz
        password: public

log:
  level: info
