# data integration

# connectors used by sources or sinks
connectors:
  - name: conn1
    type: amqp
    enabled: true
    options:
      url: amqp://guest:guest@localhost:5672/
  - name: mqtt
    type: mqtt
    enabled: false
    options:
      clientId: $rule
      host: localhost
      port: 1883
      user: $tio
      password: public
      cleanSession: false

# data sources
sources:
  - name: src1
    type: embed-mqtt
    enabled: true
    options:
      topic: $iothub/things/+/presence
      qos: 1
  - name: src2
    type: embed-mqtt
    enabled: false
    options:
      topic: $iothub/user/things/+/property
      qos: 1
  - name: src-mqtt
    type: mqtt
    connector: mqtt
    options:
      topic: $iothub/user/things/+/test
      qos: 1
# data sinks
sinks:
  - name: sink1
    type: amqp
    connector: conn1
    enabled: true
    options:
      exchange: exch1
      routingKey: 
  - name: mqtt
    type: mqtt
    connector: mqtt
    enabled: false
    options:
      topic: $iothub/user/things/${thingId}/publish

# Sources --> Process(filter and transform chain) --> Sinks
# Only json messages are supported
#
# processing message using gojq https://github.com/itchyny/gojq
#
# Message format :
# {
#   "thingId": "thignId",
#   "topic": "message/mqtt/topic"
#   "payload": {
#     "a": "a value of message payload"
#   } 
# }
rules:
  - name: test-rule
    note: test
    enabled: true
    sources:
      - src1
      - src2
      - src-mqtt
    process:
      - type: filter
        name: keep-bigger-than-10
        # runner: jq  # can be omitted when the js field is empty
        jq: ".payload.data.a > 10"  # should return true of false result
      - type: filter
        name: keep-less-than-100
        # runner: js # can be omitted when the jq field is empty
        js: "function run(d) { return d.payload.data.a > 10 }"
      - type: transform
        name: to-field-x
        jq: "{ X: .payload.data.a }" # result like: {"X": 11}
      - type: transform
        name: to-field-y
        js: "function run(d) { return { Y: d.payload.data.a } }" # result like: {"Y": 11}
    sinks:
      - sink1
      - mqtt
