# data integration

# connectors used by sources or sinks
connectors:
  - name: test-conn
    type: amqp
    options:
      url: amqp://guest:guest@localhost:5672/

# data sources
sources:
  - name: test-src1
    type: embed-mqtt
    options:
      topic: $iothub/things/#
      qos: 1
  - name: test-src2
    type: embed-mqtt
    options:
      topic: $iothub/user/things/+/property
      qos: 1
# data sinks
sinks:
  - name: test-sink
    type: amqp
    connector: test-conn
    options:
      exchange: dev-tio
      routingKey: 

# Sources --> Process(filter and transform) --> Sinks
# Only json messages are supported
#
# processing message using gojq https://github.com/itchyny/gojq
#
# Message format :
# {
#   "thingId": "thignId",
#   "topic": "message/mqtt/topic"
#   "payload": {
#     "a": "a value of message payload"
#   } 
# }

# rules:
#   - name: test-rule
#     sources:
#       - test-src1
#       - test-src2
#     process:
#       - type: filter
#         name: keep-bigger-than-10
#         jq: ".payload.data.a > 10"
#       - type: transform
#         name: to-field-x
#         jq: "{ X: .payload.data.a }"
#     sinks:
#       - test-sink
