# data integration

# connectors used by sources or sinks
connectors:
  - name: conn1
    type: amqp
    options:
      url: amqp://guest:guest@localhost:5672/

# data sources
sources:
  - name: src1
    type: embed-mqtt
    options:
      topic: $iothub/things/+/presence
      qos: 1
  - name: src2
    type: embed-mqtt
    options:
      topic: $iothub/user/things/+/property
      qos: 1
# data sinks
sinks:
  - name: sink1
    type: amqp
    connector: conn1
    options:
      exchange: exch1
      routingKey: 

# Sources --> Process(filter and transform chain) --> Sinks
# Only json messages are supported
#
# processing message using gojq https://github.com/itchyny/gojq
#
# Message format :
# {
#   "thingId": "thignId",
#   "topic": "message/mqtt/topic"
#   "payload": {
#     "a": "a value of message payload"
#   } 
# }
rules:
  - name: test-rule
    sources:
      - src1
      - src2
    process:
      - type: filter
        name: keep-bigger-than-10
        jq: ".payload.data.a > 10"  # should return true of false result
      - type: transform
        name: to-field-x
        jq: "{ X: .payload.data.a }" # result like: {"X": 11}
    sinks:
      - sink1
