// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gorm.io/gorm"
	"ruff.io/tio/job"
	"ruff.io/tio/pkg/uuid"
)

// Injectors from wire.go:

func InitSvc(dbConn *gorm.DB, jc job.Center) job.MgrService {
	repo := job.NewRepo(dbConn)
	idProvider := uuid.New()
	mgrService := job.NewMgrService(repo, idProvider, jc)
	return mgrService
}
